name: myfirstactionproject

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  buildnow:
    runs-on: ubuntu-latest

    steps:
      - name: Download the code from Git
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Check Java Version
        run: java --version

      - name: Install Maven
        run: |
          sudo apt update -y
          sudo apt install maven -y
      - name: Check Maven Version
        run: mvn --version
      - name: build the artifacts
        run:  mvn clean package
      - name: check the war file
        run: ls -ltr target
      - name: Upload war Artifact
        uses: actions/upload-artifact@v4
        with:
          name: appjava
          path: target/*.war
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

















        
        
        
        
